"use client";
import { useState } from "react";
import type { DemoState } from "@/lib/types";
import type { DemoAction } from "@/lib/payroll/state";
import { actionMode } from "@/lib/payroll/state";
import { METRICS, SOURCE_LABELS, fmt } from "@/lib/payroll/model";
import { Modal, SourceBadge } from "./ui";

export function ActionInspector({state,id,send,onClose,onEmployee}:{state:DemoState;id:string;send:(a:DemoAction)=>void;onClose:()=>void;onEmployee:(id:string,control?:string)=>void}) {
  const [ack,setAck]=useState(false);const a=state.actions.find(x=>x.id===id);if(!a)return null;
  const mode=actionMode(state,a.kind),now=()=>new Date().toISOString();
  const explanation={proposed:"This is a proposal. Original snapshots have not changed.",authorized:"This exact simulated action is authorized. No request has been executed yet.","verification-pending":"A request or manual update was reported. Destination evidence must be read back before this action is considered successful.",uncertain:"Delivery is uncertain. Do not blindly retry; inspect the destination using the original action receipt.",verified:"The synthetic destination evidence matches the intended change. Other systems have not been silently changed.",invalidated:"This proposal was cancelled or its evidence was superseded. Prepare a fresh proposal before acting.",failed:"The destination did not match the proposal. The action is not verified; inspect the remaining discrepancy."}[a.status];
  return <Modal title={a.title} subtitle="Controlled action · synthetic demonstration" onClose={onClose} wide>{state.notice&&<p className="inlineNotice" role="status">{state.notice}</p>}<div className="actionState"><SourceBadge source={a.target}/><strong>{a.status.replaceAll("-"," ")}</strong><span>{a.id}</span></div><p className="actionExplanation">{explanation}</p><div className="readOnlyNotice">No real system is changed. Action authorization is not payroll approval or submission.</div><dl className="proposalFacts"><div><dt>Target</dt><dd>{SOURCE_LABELS[a.target]}</dd></div><div><dt>Finding</dt><dd>{a.reason}</dd></div><div><dt>Execution policy</dt><dd>{mode==="manual"?"Human updates the source; tool verifies":mode==="preview"?"Prepare and preview; no tool execution":"Execute only after action authorization"}</dd></div><div><dt>Receipt</dt><dd>{a.receipt??"Not executed"}</dd></div><div><dt>Read-back evidence</dt><dd>{a.verifiedSnapshotId??"Not yet verified"}</dd></div></dl>
    {a.changes.length>0&&<div className="tableScroll"><table className="detailTable proposalTable"><thead><tr><th>Employee</th><th>Field</th><th>Before</th><th>Proposed</th></tr></thead><tbody>{a.changes.map((c,i)=><tr key={`${c.employeeId}-${c.metric}-${i}`}><td>{state.dataset.employees.find(e=>e.id===c.employeeId)?.name}</td><td>{METRICS[c.metric].label}</td><td>{fmt(c.before,c.metric)}</td><td><strong>{fmt(c.after,c.metric)}</strong></td></tr>)}</tbody></table></div>}
    {a.payloadLines&&<details className="evidenceDetails"><summary>Inspect {a.payloadLines.length} intended payroll lines</summary><p>Normalized target-specific preview. Production vendor format, endpoint, access and validation must be confirmed before any real transfer.</p><div className="tableScroll"><table className="detailTable"><thead><tr><th>Employee</th><th>Component</th><th>Value</th><th>Code / job</th></tr></thead><tbody>{a.payloadLines.slice(0,60).map((l,i)=><tr key={`${l.id}-${i}`}><td>{l.sourceEmployeeId}</td><td>{METRICS[l.metric].label}</td><td>{fmt(l.value,l.metric)}</td><td>{l.code} · {l.job}</td></tr>)}</tbody></table></div>{a.payloadLines.length>60&&<p>First 60 lines shown; all lines remain available in the technical preview below.</p>}<details><summary>Technical preview — all lines</summary><pre className="technicalPreview">{JSON.stringify(a.payloadLines,null,2)}</pre></details></details>}
    <div className="actionProgress" aria-label="Action progress">{["Propose","Authorize / manual handoff","Receipt","Read back","Verify"].map((label,i)=><span key={label}><b>{i+1}</b>{label}</span>)}</div>
    {a.status==="proposed"&&<section className="actionControls">{mode==="approval"?<><label className="checkControl"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I authorize this exact simulated action, not payroll approval.</label><button className="primaryButton" disabled={!ack} onClick={()=>{send({type:"AUTHORIZE",id:a.id,at:now()});setAck(false);}}>Authorize action (demo)</button></>:<><p>{mode==="preview"?"The tool is limited to preparing this preview. Payroll can use the existing manual source-system process.":"Payroll would perform this change in the source system, then return for verification."}</p><button className="secondaryButton" onClick={()=>send({type:"EXTERNAL_UPDATE",id:a.id,at:now()})}>{a.kind==="mapping"?"Simulate mapping confirmed by Payroll":`Simulate manual update in ${SOURCE_LABELS[a.target]}`}</button></>}<button className="textButton" onClick={()=>send({type:"CANCEL",id:a.id,at:now()})}>Cancel proposal</button></section>}
    {a.status==="authorized"&&<div className="buttonRow"><button className="primaryButton" onClick={()=>send({type:"EXECUTE",id:a.id,at:now()})}>Simulate execution</button><button className="textButton" onClick={()=>send({type:"CANCEL",id:a.id,at:now()})}>Cancel before execution</button></div>}
    {["verification-pending","uncertain"].includes(a.status)&&<div className="buttonRow"><button className="primaryButton" onClick={()=>send({type:"VERIFY",id:a.id,at:now()})}>Read back and verify (demo)</button><span className="muted">Retry disabled while the outcome is unverified.</span></div>}
    {a.status==="verified"&&a.employeeId&&<button className="primaryButton" onClick={()=>onEmployee(a.employeeId!,a.controlId)}>Inspect updated employee evidence</button>}
    <details className="evidenceDetails"><summary>Version binding and duplicate protection</summary><p>This proposal is bound to the exact source snapshots and rule version below. Changed evidence invalidates authorization. Duplicate execution of this action is blocked.</p><pre className="technicalPreview">{a.evidenceKey}</pre><p>{a.authorizedBy?`Authorized by ${a.authorizedBy} — simulated role, not real authentication.`:"No tool execution authorization recorded."}</p></details>
  </Modal>;
}
