"use client";
import { useState } from "react";
import type { AutomationPolicy, ControlResult, DemoState, Scenario, View } from "@/lib/types";
import type { DemoAction } from "@/lib/payroll/state";
import { DEFAULT_POLICY } from "@/lib/payroll/state";
import { SCENARIOS } from "@/data/demo";
import { sourceUsable } from "@/lib/payroll/model";
import { comparisonCsv, download, reviewHtml } from "@/lib/payroll/export";
import { Modal, PageHeading, SourceBadge, StatusBadge, timeLabel } from "./ui";

export function AutomationOptions({state,send,onClose}:{state:DemoState;send:(a:DemoAction)=>void;onClose:()=>void}) {
  const [draft,setDraft]=useState<AutomationPolicy>({...state.policy});
  const field=(key:keyof AutomationPolicy,value:string)=>setDraft({...draft,[key]:value});
  const modes=[['manual','Manual source-system action'],['preview','Prepare / preview only'],['approval','Execute after action authorization']] as const;
  return <Modal title="Automation options" subtitle="Configuration preview · B&S chooses the boundary" onClose={onClose} wide><p className="dialogLead">Choose how work is performed—not which payroll values are considered correct. Changing this policy does not execute an action.</p><div className="readOnlyNotice">All source-system actions remain simulated. Production access, vendor support and B&S authorization must be confirmed per operation.</div><div className="presetRow"><span>Explore a starting point</span><button className="secondaryButton compact" onClick={()=>setDraft({...DEFAULT_POLICY})}>Observe and verify</button><button className="secondaryButton compact" onClick={()=>setDraft({...DEFAULT_POLICY,preparation:"automatic",transfer:"preview",corrections:"preview"})}>Prepare and preview</button><button className="secondaryButton compact" onClick={()=>setDraft({...DEFAULT_POLICY,preparation:"automatic",transfer:"approval",corrections:"approval",closeout:"approval"})}>Approval-gated execution</button></div>
    <div className="policyRows"><label><span><strong>Collect source evidence</strong><small>Manual import or future scheduled collection. Comparison controls run in both modes.</small></span><select aria-label="Collection policy" value={draft.collection} onChange={e=>field("collection",e.target.value)}><option value="manual">Manual evidence import</option><option value="automatic">Automatic collection (demo)</option></select></label><label><span><strong>Prepare payroll inputs</strong><small>Apply explicit mappings and documented rules; ambiguous cases still stop for Payroll.</small></span><select aria-label="Preparation policy" value={draft.preparation} onChange={e=>field("preparation",e.target.value)}><option value="preview">Preview on request</option><option value="automatic">Prepare validated inputs automatically</option></select></label>{([['transfer','Transfer payroll','Jonas preparation / Paylocity transfer'],['corrections','Correct source records','An exact proposal with evidence and a destination'],['closeout','Jonas closeout','Only after separately recorded human submission']] as const).map(([key,label,hint])=><label key={key}><span><strong>{label}</strong><small>{hint}</small></span><select aria-label={`${label} policy`} value={draft[key]} onChange={e=>field(key,e.target.value)}>{modes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>)}<div className="lockedPolicy"><span><strong>Approve payroll</strong><small>Human decision in Paylocity</small></span><strong>Human required · fixed</strong></div><div className="lockedPolicy"><span><strong>Submit payroll</strong><small>Separate human action in Paylocity</small></span><strong>Human required · fixed</strong></div></div>
    <p className="panelFootnote">IT integration administration does not grant payroll approval authority. Actual authentication and roles are outside this synthetic demo.</p><div className="buttonRow"><button className="primaryButton" onClick={()=>{send({type:"POLICY",policy:draft,at:new Date().toISOString()});onClose();}}>Apply demo policy</button><button className="secondaryButton" onClick={onClose}>Cancel</button></div></Modal>;
}
export function DemoControls({state,send,onClose,externalDemo,onExternal,onReset}:{state:DemoState;send:(a:DemoAction)=>void;onClose:()=>void;externalDemo:boolean;onExternal:(b:boolean)=>void;onReset:(s:Scenario)=>void}) {
  const [scenario,setScenario]=useState<Scenario>(state.scenario),[confirm,setConfirm]=useState(false);
  return <Modal title="Demo controls" subtitle="Presentation tools · no production settings" onClose={onClose}><p className="dialogLead">Scenario changes replace the current browser-session data, proposals and audit history. They never affect real systems.</p><label className="fieldLabel">Scenario<select value={scenario} onChange={e=>{setScenario(e.target.value as Scenario);setConfirm(false);}} aria-label="Demo scenario">{Object.entries(SCENARIOS).map(([id,s])=><option key={id} value={id}>{s.label}</option>)}</select></label><p>{SCENARIOS[scenario].description}</p><label className="checkControl"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Replace the current synthetic session with this scenario.</label><button className="primaryButton" disabled={!confirm} onClick={()=>onReset(scenario)}>Load / reset scenario</button><hr/><label className="fieldLabel">Next simulated execution outcome<select aria-label="Simulated execution outcome" value={state.outcome} onChange={e=>send({type:"OUTCOME",outcome:e.target.value as DemoState['outcome'],at:new Date().toISOString()})}><option value="normal">Normal destination read-back</option><option value="uncertain">Uncertain delivery — verify before retry</option><option value="mismatch">Destination does not match the proposal</option></select></label><p className="panelFootnote">This demonstrates receipt versus verification. An uncertain action cannot be blindly retried.</p><hr/><label className="checkControl"><input type="checkbox" checked={externalDemo} onChange={e=>onExternal(e.target.checked)}/>Show the external approval, submission and closeout illustration.</label><p className="panelFootnote">These are records of fictional human steps performed outside the tool. They are not live payroll actions.</p></Modal>;
}
export function QuickGuide({onClose,onStart}:{onClose:()=>void;onStart:()=>void}) {
  return <Modal title="How to read Reconciliation" subtitle="Quick guide" onClose={onClose}><p className="dialogLead">One workspace for the payroll handoffs, checks and decisions currently spread across several systems and reports.</p><div className="guideSteps"><div><span className="guideNumber">1</span><div><strong>Start with what needs attention.</strong><span>Routine comparisons run automatically. Payroll investigates exceptions, not every repeated comparison.</span></div></div><div><span className="guideNumber">2</span><div><strong>Trace the evidence.</strong><span>See original values, approvals, documented adjustments and destination verification. A first mismatch narrows investigation; it does not prove the cause.</span></div></div><div><span className="guideNumber">3</span><div><strong>Explore how much work to automate.</strong><span>Payroll process shows preparation, transfers and action authorization. B&S chooses the permitted level; human payroll approval and submission stay separate.</span></div></div></div><div className="guideSourceLegend"><div><SourceBadge source="raken"/><span>Field time and project evidence</span></div><div><SourceBadge source="jonas"/><span>Prepared payroll, accounting and job cost</span></div><div><SourceBadge source="paylocity"/><span>Employee checks and payroll processing</span></div><div><SourceBadge source="inputs"/><span>Salary / leave, per-diem tracker and other approved inputs</span></div></div><div className="guideCaution"><strong>Reconciled ≠ identical raw values ≠ submitted.</strong><span>A documented transformation can explain a valid difference. Required controls must pass against current evidence. Payroll still makes the final human decisions.</span></div><p>View all employees and export a review packet whenever you need independent reassurance. All future execution shown here is simulated.</p><div className="buttonRow"><button className="primaryButton" onClick={onStart}>Start guided walkthrough</button><button className="secondaryButton" onClick={onClose}>Return to payroll</button></div></Modal>;
}
export function Walkthrough({step,onStep,onClose}:{step:number;onStep:(s:number)=>void;onClose:()=>void}) {
  const copy=[['One payroll workspace','Inputs, prepared payroll and final checks are visible together. The summary is backed by employee-level evidence.'],['Choose the automation boundary','Explore automation options. B&S can start read-only, then prepare inputs or authorize supported actions later.'],['Human attention goes here','Every open control remains visible. Reviewing a difference does not silently change or approve payroll.'],['Every result is inspectable','This valid 38 → 40 adjustment keeps the original source time, the documented rule and both downstream values visible.'],['The human decision remains separate','Automation prepares evidence for approval. A person still approves and submits in Paylocity as distinct actions.']][step];
  return <aside className="walkthroughBar" aria-label="Presentation guidance"><span className="guideNumber">{step+1}</span><div><strong>{copy[0]}</strong><p>{copy[1]}</p></div><div className="buttonRow">{step>0&&<button className="textButton" onClick={()=>onStep(step-1)}>Back</button>}<button className="secondaryButton compact" onClick={()=>step===4?onClose():onStep(step+1)}>{step===4?"Finish":"Next"}</button><button className="iconButton" aria-label="Close walkthrough" onClick={onClose}>×</button></div></aside>;
}
export function ExportPanel({state,controls,send,onClose}:{state:DemoState;controls:ControlResult[];send:(a:DemoAction)=>void;onClose:()=>void}) {
  function run(format:"html"|"csv"|"json") {
    const content=format==="html"?reviewHtml(state,controls):format==="csv"?comparisonCsv(state,controls):JSON.stringify({notice:"SYNTHETIC DEMO ONLY — no payroll authorization",state,controls},null,2);
    download(content,`synthetic-payroll-review-${state.dataset.run.periodId}.${format}`,format==="html"?"text/html;charset=utf-8":format==="csv"?"text/csv;charset=utf-8":"application/json");
    send({type:"EXPORT",format,at:new Date().toISOString()});
  }
  return <Modal title="Manual review packet" subtitle="All employees · current evidence and control results" onClose={onClose}><p>Continue independent review without being trapped in the application. Exports include source versions and unresolved controls; they do not certify stale or missing evidence.</p><div className="exportChoices"><button className="secondaryButton" onClick={()=>run("html")}><strong>Readable review packet</strong><span>HTML · opens in a browser and can be printed</span></button><button className="secondaryButton" onClick={()=>run("csv")}><strong>Spreadsheet-friendly comparisons</strong><span>CSV · all employee and run-level controls</span></button></div><details className="evidenceDetails"><summary>Technical evidence export</summary><p>Full synthetic source snapshots, history, proposals and audit events.</p><button className="secondaryButton" onClick={()=>run("json")}>Download JSON evidence</button></details><div className="readOnlyNotice">Synthetic review material only. Not an import file and not payroll approval.</div>{state.notice&&<p role="status" className="inlineNotice">{state.notice}</p>}</Modal>;
}
export function Integrations({state,controls,send}:{state:DemoState;controls:ControlResult[];send:(a:DemoAction)=>void}) {
  const d=state.dataset;
  return <section className="pageStack"><PageHeading title="Source evidence and integrations" description="IT would manage production connections in the backend. Payroll sees availability and evidence here—not a request to connect its tools. This demo has no live connections."/><div className="integrationGrid">{(['raken','jonas','paylocity'] as const).map(source=>{const s=d.snapshots[source];return <article className="integrationCard" key={source}><div className="integrationTop"><SourceBadge source={source}/><span className="connectedTag">Simulated source</span></div><dl><div><dt>Live connection</dt><dd>Not connected</dd></div><div><dt>Snapshot</dt><dd>{s.id} · {s.health}</dd></div><div><dt>Evidence time</dt><dd>{timeLabel(s.capturedAt)}</dd></div><div><dt>Pay period</dt><dd>{s.periodId}</dd></div><div><dt>Rows available</dt><dd>{s.lines.length}</dd></div></dl><details className="evidenceDetails"><summary>Future supported integration path</summary><p>{source==='raken'?'Approved API / export. Confirm worker identity, approval evidence and permitted operations.':source==='jonas'?'Vendor-supported reporting / import interface. Confirm B&S version, licensing and each payroll operation; general write capability is not assumed.':'Approved developer endpoints / payroll reports. Confirm company access, endpoint permissions and processing / read-back behavior.'}</p><p>Vendor secrets remain server-side. This public synthetic demo contains no credentials.</p></details>{s.health!=="not-loaded"&&<button className="secondaryButton fullWidth" onClick={()=>send({type:"REFRESH",source,at:new Date().toISOString()})}>Refresh synthetic evidence</button>}</article>;})}</div><section className="panel"><div className="panelHeader"><div><p className="sectionKicker">Supporting payroll inputs</p><h3>Not every value comes from Raken</h3></div><SourceBadge source="inputs"/></div><p className="panelBody">Salary / leave input, per-diem tracker, and illustrative approved pay / deduction setup are separate source evidence. Production ownership and approvals need B&S confirmation.</p><div className="reportList">{d.snapshots.inputs.reports.map(r=><div key={r.name}><span>{r.name}</span><strong>{d.snapshots.inputs.id} · synthetic</strong></div>)}</div></section><section className="panel"><div className="panelHeader"><h3>Run-level evidence controls</h3></div><div className="readinessRows">{controls.filter(c=>!c.employeeId).map(c=><div key={c.id}><span><strong>{c.title}</strong><small>{c.detail}</small></span><StatusBadge state={c.state}/></div>)}</div></section><p className="panelFootnote">{Object.values(d.snapshots).filter(s=>sourceUsable(d,s.source)).length} of 4 evidence groups are current for this synthetic run. Unavailable evidence never becomes a green approval-ready status.</p></section>;
}
export function AuditTrail({state,onExport,onNavigate}:{state:DemoState;onExport:()=>void;onNavigate:(v:View)=>void}) {
  const [query,setQuery]=useState("");const events=state.audit.filter(e=>`${e.type} ${e.detail} ${e.employeeId??''}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="pageStack"><PageHeading title="Audit trail" description="Source snapshots, decisions, proposed actions and read-back verification remain separate events. This history is synthetic and browser-session only—not a production audit store." action={<button className="secondaryButton" onClick={onExport}>Export review packet</button>}/><label className="fieldLabel auditSearch">Filter this session<input aria-label="Search audit history" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Action, employee ID or finding"/></label><div className="auditTimeline">{events.map(e=><article key={e.id}><div className="auditEventHeading"><strong>{e.type}</strong><time dateTime={e.at}>{timeLabel(e.at)}</time></div><p>{e.detail}</p><small>{e.actor}{e.employeeId?` · ${e.employeeId}`:''}</small><details><summary>Evidence and before / after values</summary><p>{e.evidenceIds.join(' · ')}</p>{e.actionId&&<p>Action: {e.actionId}</p>}{e.changes&&<pre className="technicalPreview">{JSON.stringify(e.changes,null,2)}</pre>}</details></article>)}</div>{!events.length&&<p>No audit events match this search.</p>}<button className="textButton" onClick={()=>onNavigate('process')}>Return to payroll process →</button></section>;
}
