"use client";
import { useState } from "react";
import type { ControlResult, DemoState, View } from "@/lib/types";
import type { DemoAction } from "@/lib/payroll/state";
import { preparationReady, visibleIssues } from "@/lib/reconciliation";
import { processStages, readiness } from "@/lib/payroll/workflow";
import { preparedLines, preparedValue } from "@/lib/payroll/preparation";
import { METRICS, SOURCE_LABELS, fmt } from "@/lib/payroll/model";
import { download, preparationCsv } from "@/lib/payroll/export";
import { Modal, PageHeading, SourceBadge } from "./ui";

type ProposalRequest=Omit<Extract<DemoAction,{type:"PROPOSE"}>,"type"|"at">;
function initialStage(state: DemoState, controls: ControlResult[], tour: number | null) {
  if (tour === 4) return "approval";
  const gate = readiness(state, controls);
  if (gate.submitted) return state.closed ? "closeout" : "closeout";
  if (gate.approved) return "submission";
  if (gate.ready) return "approval";
  const issues = visibleIssues(controls);
  if (issues.some(c => c.boundary === "jonas-paylocity") && state.dataset.snapshots.paylocity.health !== "not-loaded") return "reconciliation";
  if (issues.some(c => c.boundary === "raken-jonas" || c.boundary === "inputs-jonas")) return "preparation";
  if (state.dataset.snapshots.jonas.health === "not-loaded") return "preparation";
  if (state.dataset.snapshots.paylocity.health === "not-loaded") return "transfer";
  return "reconciliation";
}

export function PayrollProcess({state,controls,onPolicy,onPrepare,onNavigate,onPropose,onAction,send,externalDemo,tour}:{state:DemoState;controls:ControlResult[];onPolicy:()=>void;onPrepare:()=>void;onNavigate:(view:View)=>void;onPropose:(p:ProposalRequest)=>void;onAction:(id:string)=>void;send:(a:DemoAction)=>void;externalDemo:boolean;tour:number|null}) {
  const [selected,setSelected]=useState(() => initialStage(state,controls,tour));
  const stages=processStages(state,controls),current=stages.find(s=>s.id===selected)??stages[0];
  const gate=readiness(state,controls),d=state.dataset;
  const active=state.actions.filter(a=>!["invalidated","failed"].includes(a.status));
  const now=()=>new Date().toISOString();
  return <section className="pageStack"><PageHeading title="Payroll process" description="See the work leading to the human decision. B&S can choose which tasks to observe, prepare or execute after authorization; payroll approval and submission remain separate." action={<button className={`secondaryButton ${tour===1?"tourTarget":""}`} onClick={onPolicy}>Explore automation options</button>}/>
    <div className="processLayout"><nav className="stageList" aria-label="Payroll stages">{stages.map((s,i)=><button className={`stageButton ${current.id===s.id?"selected":""}`} key={s.id} aria-current={current.id===s.id?"step":undefined} onClick={()=>setSelected(s.id)}><span className="stepIndex">{i+1}</span><span><strong>{s.title}</strong><small>{s.status}</small></span>{["approval","submission"].includes(s.id)&&<span className="humanTag">Human</span>}</button>)}</nav>
    <section className={`processPane ${tour===4&&["approval","submission"].includes(current.id)?"tourTarget":""}`}><div className="processPaneHeader"><span className="stageEyebrow">Stage {stages.findIndex(s=>s.id===current.id)+1} of {stages.length}</span><h3>{current.title}</h3><p className="stageState">{current.status}</p><p>{current.detail}</p></div><div className="stageControls"><div><span>Automation scope</span><strong>{current.automation}</strong></div><div><span>Human control</span><strong>{current.human}</strong></div></div>
      {current.id==="inputs"&&<><div className="readinessGrid">{(["raken","jonas","paylocity"] as const).map(s=>{const expected=d.employees.filter(e=>s!=="raken"||e.role!=="Salary"),mapped=expected.filter(e=>e.ids[s]&&d.employees.filter(x=>x.ids[s]===e.ids[s]).length===1).length;return <div key={s}><SourceBadge source={s}/><strong>{mapped} / {expected.length}</strong><span>Expected employee identities mapped</span></div>;})}</div><p className="panelFootnote">Salary / leave, per-diem tracker and other payroll inputs remain supporting evidence—not fictional Raken records.</p><div className="buttonRow"><button className="secondaryButton" onClick={()=>onNavigate("integrations")}>Inspect evidence readiness</button><button className="textButton" onClick={()=>send({type:"REFRESH",at:now()})}>{state.policy.collection==="automatic"?"Simulate scheduled refresh":"Import fresh synthetic snapshots"}</button></div></>}
      {current.id==="preparation"&&<><div className="preparationCallout"><strong>38 recorded hours → 40 payroll-ready hours</strong><span>An approved, applicable demo rule explains the difference. Original evidence is retained.</span></div><p>{visibleIssues(controls).filter(c=>["raken-jonas","inputs-jonas"].includes(c.boundary)).length} upstream controls need review. The preview includes field, driver and salary paths; deductions and per diem retain separate components.</p><button className="primaryButton" onClick={onPrepare}>{state.policy.preparation==="automatic"?"Inspect automatically prepared input":"Preview Jonas-ready input"}</button></>}
      {current.id==="jonas"&&<><div className="reportList">{d.snapshots.jonas.reports.length?d.snapshots.jonas.reports.map(r=><div key={r.name}><span>{r.name}</span><strong>{r.revision===d.snapshots.jonas.revision?"Current demo evidence":"Superseded"}</strong></div>):<p>No Jonas report evidence yet. The preparation walkthrough can simulate the handoff and subsequent report read-back.</p>}</div><div className="buttonRow"><button className="secondaryButton" onClick={onPrepare}>{d.snapshots.jonas.health==="not-loaded"?"Prepare the Jonas handoff":"Inspect prepared input"}</button>{d.snapshots.jonas.health!=="not-loaded"&&<button className="textButton" onClick={()=>send({type:"REFRESH",source:"jonas",at:now()})}>Load updated demo reports</button>}</div></>}
      {current.id==="transfer"&&<><div className="handoffPath"><SourceBadge source="jonas"/><span>Prepared payroll → import receipt → read-back</span><SourceBadge source="paylocity"/></div><p>{d.snapshots.paylocity.health==="not-loaded"?"The next handoff can be prepared only after source readiness and Jonas controls pass.":"A batch is already represented. Use targeted corrections instead of repeating a full import."}</p><button className="primaryButton" disabled={d.snapshots.paylocity.health!=="not-loaded"} onClick={()=>onPropose({kind:"paylocity-transfer",note:"Synthetic handoff: current Jonas reports reviewed for the selected payroll run."})}>{state.policy.transfer==="approval"?"Review proposed transfer":state.policy.transfer==="preview"?"Prepare transfer preview":"Prepare manual transfer"}</button></>}
      {current.id==="reconciliation"&&<><div className="handoffPath"><SourceBadge source="jonas"/><span>Pay Journal ↔ Pre Process Payroll Register</span><SourceBadge source="paylocity"/></div><p>Hours, PTO / holiday, both per-diem categories, deductions, rates and check completeness are compared. A required input that is unavailable cannot become a passing control.</p><div className="buttonRow"><button className="primaryButton" onClick={()=>onNavigate("exceptions")}>Review exceptions</button><button className="secondaryButton" onClick={()=>onNavigate("employees")}>Inspect all employees</button></div></>}
      {current.id==="approval"&&<div className="humanGate"><strong>Human payroll approval in Paylocity</strong><p>{gate.ready?"Required demo controls passed. Payroll can now make the approval decision in Paylocity.":"Required controls or pending actions still need attention. This app withholds its ready status; it does not technically prevent someone acting directly in Paylocity."}</p><span>Automated approval: not implemented</span>{externalDemo&&<button className="secondaryButton" disabled={!gate.ready||gate.approved} onClick={()=>send({type:"EXTERNAL_APPROVAL",at:now()})}>Illustrate external approval evidence (demo)</button>}</div>}
      {current.id==="submission"&&<div className="humanGate"><strong>A separate human submission</strong><p>After approval, Payroll reviews the Paylocity audit and submits there. Neither a green comparison nor action authorization submits payroll.</p><span>Automated submission: not implemented</span>{externalDemo&&<button className="secondaryButton" disabled={!gate.approved||gate.submitted} onClick={()=>send({type:"EXTERNAL_SUBMISSION",at:now()})}>Illustrate external submission evidence (demo)</button>}</div>}
      {current.id==="closeout"&&<><div className="reportList">{["Batch Accrual of T&A Hrs","Cost Allocation Report","End of Payroll Update","Completion notification"].map(label=><div key={label}><span>{label}</span><strong>{state.closed?"Illustrative evidence recorded":"Not performed here"}</strong></div>)}</div><p className="panelFootnote">This preview contains no period-close operation and sends no email.</p>{externalDemo&&(state.policy.closeout==="approval"?<button className="primaryButton" disabled={!gate.submitted||state.closed} onClick={()=>onPropose({kind:"closeout",note:"Synthetic closing reports reviewed after externally recorded human submission."})}>Preview controlled closeout</button>:<button className="secondaryButton" disabled={!gate.submitted||state.closed} onClick={()=>send({type:"EXTERNAL_CLOSEOUT",at:now()})}>Illustrate manual closeout evidence (demo)</button>)}</>}
      {!externalDemo&&["approval","submission","closeout"].includes(current.id)&&<p className="panelFootnote">The optional post-reconciliation illustration can be enabled in Demo controls. It never performs these actions in a real system.</p>}
    </section></div>
    {active.length>0&&<section className="panel"><div className="panelHeader"><div><p className="sectionKicker">Proposals and receipts</p><h3>Follow work through verification</h3></div></div><div className="actionList">{active.map(a=><button key={a.id} onClick={()=>onAction(a.id)}><span><strong>{a.title}</strong><small>{SOURCE_LABELS[a.target]} · {a.id}</small></span><span className={`actionStatus ${a.status}`}>{a.status.replaceAll("-"," ")}</span><span>Inspect →</span></button>)}</div></section>}
    <details className="evidenceDetails"><summary>Demonstration coverage and production boundaries</summary><p>Working with synthetic data: employee mapping, preparation expectations, stage-specific comparisons, source freshness, trace, proposals, receipts, read-back, audit and exports. Vendor report results are simulated evidence, not calculations performed by this application.</p><p>Future integrations require B&S-approved interfaces, licenses, field mappings and private infrastructure. Detailed payroll calculations, taxes, funding, complex retroactive adjustments and final release remain source-system / human responsibilities, not capabilities claimed by this demo.</p></details>
  </section>;
}
export function PreparationPreview({state,controls,onClose,onPropose,onEmployee,send}:{state:DemoState;controls:ControlResult[];onClose:()=>void;onPropose:(p:ProposalRequest)=>void;onEmployee:(id:string)=>void;send:(a:DemoAction)=>void}) {
  const [all,setAll]=useState(false),lines=preparedLines(state.dataset),d=state.dataset,ready=preparationReady(d);
  const issues=visibleIssues(controls).filter(c=>["raken-jonas","inputs-jonas"].includes(c.boundary));
  const expected=d.employees.filter(e=>e.expectedPay);
  const foreman=d.employees.find(e=>e.id==="EMP-1005")!,p=preparedValue(d,foreman,"regular");
  return <Modal title="Payroll preparation preview" subtitle="Phase 2 · normalized synthetic input" onClose={onClose} wide><div className="readOnlyNotice">Preview only—not a vendor-approved import file. No payroll data has been sent to Jonas.</div><div className="preparationStats"><div><strong>{expected.length}</strong><span>Expected employees</span></div><div><strong>{lines.length}</strong><span>Prepared component lines</span></div><div><strong>{issues.length}</strong><span>Upstream controls need review</span></div></div><div className="preparationCallout"><strong>{foreman.name} · {fmt(p.raw,"regular")} → {fmt(p.value,"regular")}</strong><span>{p.rule}</span><button className="textButton" onClick={()=>onEmployee(foreman.id)}>Trace this expected adjustment →</button></div>
    {!ready&&<p className="warningBanner">Handoff blocked. Resolve input, identity and mapping issues before treating these lines as ready for Jonas.</p>}
    <div className="tableScroll"><table className="detailTable"><thead><tr><th>Employee</th><th>Component</th><th>Payroll-ready value</th><th>Code / job</th></tr></thead><tbody>{(all?lines:lines.slice(0,27)).map(l=><tr key={l.id}><td>{d.employees.find(e=>e.id===l.employeeId)?.name}<small>{l.sourceEmployeeId}</small></td><td>{METRICS[l.metric].label}</td><td>{fmt(l.value,l.metric)}</td><td>{l.code} · {l.job}</td></tr>)}</tbody></table></div><div className="buttonRow"><button className="textButton" onClick={()=>setAll(!all)}>{all?"Show fewer lines":`Show all ${lines.length} lines`}</button><button className="secondaryButton" onClick={()=>{download(preparationCsv(state,lines),"synthetic-preparation-preview-NOT-FOR-IMPORT.csv","text/csv;charset=utf-8");send({type:"EXPORT",format:"preparation preview (not an import file)",at:new Date().toISOString()});}}>Download preview CSV</button></div><div className="resolutionPanel"><h3>Next handoff</h3><p>{d.snapshots.jonas.health==="not-loaded"?"The selected automation policy controls whether Payroll performs a manual handoff or authorizes a simulated tool action.":"Jonas already contains this payroll. A full re-import is blocked to avoid duplicating entries; investigate individual discrepancies instead."}</p><button className="primaryButton" disabled={!ready||d.snapshots.jonas.health!=="not-loaded"} onClick={()=>onPropose({kind:"jonas-input",note:"Payroll-ready synthetic inputs reviewed; mappings and documented rules verified."})}>Prepare Jonas handoff</button></div></Modal>;
}
